//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_04.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_04.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31-31,32-40
        ///26-92,13-91
        ///9-90,29-91
        ///72-72,25-73
        ///28-79,79-79
        ///52-77,53-53
        ///17-54,17-54
        ///11-47,4-10
        ///1-96,1-97
        ///38-99,39-63
        ///19-54,18-53
        ///1-73,1-73
        ///17-34,18-34
        ///93-93,25-94
        ///96-98,7-95
        ///58-97,73-98
        ///7-64,8-64
        ///87-91,67-90
        ///42-78,77-85
        ///24-96,24-97
        ///71-78,72-97
        ///5-28,27-29
        ///19-86,86-90
        ///19-85,20-20
        ///64-65,1-64
        ///28-78,27-81
        ///79-91,80-95
        ///32-89,32-82
        ///3-96,2-4
        ///70-83,15-70
        ///5-90,8-91
        ///16-60,16-61
        ///38-97,39-90
        ///25-56,6-55
        ///12-14,13-13
        ///11-95,11-96
        ///13-16,12-22
        ///15-29,14-72
        ///68-88,67-69
        ///23-95,94-97
        ///63-77,62- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-4,6-8
        ///2-3,4-5
        ///5-7,7-9
        ///2-8,3-7
        ///6-6,4-6
        ///2-6,4-8.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
