//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_09.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_09.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D 2
        ///R 1
        ///L 2
        ///U 1
        ///R 2
        ///L 2
        ///R 2
        ///L 1
        ///R 1
        ///L 1
        ///R 2
        ///L 2
        ///R 1
        ///D 2
        ///U 1
        ///R 1
        ///L 2
        ///U 2
        ///R 2
        ///U 2
        ///R 2
        ///D 1
        ///L 1
        ///U 1
        ///R 2
        ///L 1
        ///D 1
        ///U 1
        ///L 1
        ///U 1
        ///D 2
        ///U 1
        ///R 2
        ///U 1
        ///L 1
        ///D 1
        ///L 1
        ///U 1
        ///R 1
        ///L 1
        ///U 2
        ///L 2
        ///D 2
        ///L 2
        ///R 2
        ///U 1
        ///R 1
        ///U 2
        ///D 2
        ///R 2
        ///L 1
        ///R 1
        ///D 1
        ///U 2
        ///R 1
        ///L 1
        ///U 2
        ///L 2
        ///U 1
        ///L 2
        ///U 1
        ///R 1
        ///L 1
        ///D 2
        ///U 2
        ///R 2
        ///D 1
        ///R 1
        ///U 2
        ///R 2
        ///L 2
        ///U 1
        ///L 1
        ///D 2
        ///R 2
        ///L 1
        ///R 1
        ///D 1
        ///R 1
        ///L 1
        ///D 2
        ///R 1
        ///U 1
        ///L 1
        ///R 1
        ///L 1
        ///D 2
        ///L 1
        ///U 1
        ///R 1
        ///D 1
        ///R 1
        ///D 1
        ///L 2
        ///U 1
        ///D 1
        ///R 2
        ///D 2
        ///R 2
        ///L 2
        ///U 2
        ///L 1
        ///U  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R 4
        ///U 4
        ///L 3
        ///D 1
        ///R 4
        ///D 1
        ///L 5
        ///R 2.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
