//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_07.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_07.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir dpbwg
        ///dir dvwfscw
        ///dir hccpl
        ///dir jsgbg
        ///dir lhjmzsl
        ///63532 mwvbpw.mmg
        ///239480 npj
        ///dir pngs
        ///dir qhs
        ///303649 shvgmwn.vhv
        ///236905 sjrrgd.phh
        ///dir sntcp
        ///dir sqs
        ///$ cd dpbwg
        ///$ ls
        ///dir dgh
        ///100731 dpbwg
        ///dir rpwnv
        ///$ cd dgh
        ///$ ls
        ///197049 lhjmzsl.hzj
        ///$ cd ..
        ///$ cd rpwnv
        ///$ ls
        ///10702 qsgv.fmf
        ///$ cd ..
        ///$ cd ..
        ///$ cd dvwfscw
        ///$ ls
        ///dir bvg
        ///dir fbfjs
        ///115450 gjftb.mgd
        ///dir gsmnprgz
        ///dir hdwdcvv
        ///dir mhjtrlqz
        ///75437 qsctddrw
        ///171722 qsgv.zqz
        ///$ cd bvg
        ///$ ls
        ///56335 cgtzb.szt
        ///139481 shvgmwn.vh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir a
        ///14848514 b.txt
        ///8504156 c.dat
        ///dir d
        ///$ cd a
        ///$ ls
        ///dir e
        ///29116 f
        ///2557 g
        ///62596 h.lst
        ///$ cd e
        ///$ ls
        ///584 i
        ///$ cd ..
        ///$ cd ..
        ///$ cd d
        ///$ ls
        ///4060174 j
        ///8033020 d.log
        ///5626152 d.ext
        ///7214296 k.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
