//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day_01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8462
        ///6981
        ///3714
        ///4409
        ///8186
        ///3614
        ///2218
        ///7558
        ///6702
        ///
        ///2947
        ///4727
        ///6396
        ///5718
        ///2361
        ///1970
        ///1583
        ///2816
        ///2995
        ///6914
        ///4313
        ///1401
        ///
        ///1643
        ///7815
        ///2162
        ///8841
        ///7671
        ///
        ///5740
        ///5471
        ///4838
        ///2281
        ///2784
        ///4587
        ///1497
        ///2074
        ///1161
        ///4388
        ///2233
        ///4795
        ///2011
        ///5438
        ///
        ///14064
        ///9646
        ///2537
        ///
        ///2064
        ///2833
        ///1164
        ///14379
        ///
        ///6008
        ///4327
        ///4709
        ///5412
        ///2745
        ///5680
        ///5322
        ///4375
        ///4064
        ///4822
        ///6523
        ///6824
        ///6822
        ///
        ///12100
        ///24791
        ///18239
        ///
        ///9704
        ///8218
        ///9949
        ///3078
        ///9407
        ///3732
        ///4281
        ///6727
        ///
        ///9833
        ///2549
        ///5042
        ///7053
        ///6116
        ///9624
        ///5393
        ///8359
        ///
        ///4195
        ///7869
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///2000
        ///3000
        ///
        ///4000
        ///
        ///5000
        ///6000
        ///
        ///7000
        ///8000
        ///9000
        ///
        ///10000.
        /// </summary>
        internal static string TestInput {
            get {
                return ResourceManager.GetString("TestInput", resourceCulture);
            }
        }
    }
}
